```yaml
server:
  port: 8080

spring:
  application:
    name: service-a
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          serviceB:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
```
